spring:
  data:
    redis:
      host: localhost
      port: 6379

account:
  clients:
    timeout: 2s
  rules:
    cache-ttl: 12h
    definitions:
      "[SAVINGS:PERSONAL:REGULAR]":
        max-owned-accounts: 1
        max-free-transactions: 20
        extra-transaction-fee: 5.00
        maintenance-fee: 0.00
        requires-active-credit-card: false
        currency: PEN
      "[SAVINGS:PERSONAL:VIP]":
        max-owned-accounts: 1
        max-free-transactions: 20
        extra-transaction-fee: 5.00
        maintenance-fee: 0.00
        requires-active-credit-card: true
        min-average-daily-balance: 1000.00
        currency: PEN
      "[CHECKING:PERSONAL:REGULAR]":
        max-owned-accounts: 1
        max-free-transactions: -1
        extra-transaction-fee: 0.00
        maintenance-fee: 25.00
        requires-active-credit-card: false
        currency: PEN
      "[CHECKING:PERSONAL:VIP]":
        max-owned-accounts: 1
        max-free-transactions: -1
        extra-transaction-fee: 0.00
        maintenance-fee: 0.00
        requires-active-credit-card: true
        currency: PEN
      "[FIXED_TERM:PERSONAL:REGULAR]":
        max-free-transactions: 1
        extra-transaction-fee: 0.00
        maintenance-fee: 0.00
        allowed-transaction-day: 15
        requires-active-credit-card: false
        currency: PEN
      "[FIXED_TERM:PERSONAL:VIP]":
        max-free-transactions: 1
        extra-transaction-fee: 0.00
        maintenance-fee: 0.00
        allowed-transaction-day: 15
        requires-active-credit-card: true
        currency: PEN
      "[CHECKING:EMPRESARIAL:REGULAR]":
        max-free-transactions: -1
        extra-transaction-fee: 0.00
        maintenance-fee: 25.00
        requires-active-credit-card: false
        currency: PEN
      "[CHECKING:EMPRESARIAL:PYME]":
        max-free-transactions: -1
        extra-transaction-fee: 0.00
        maintenance-fee: 0.00
        requires-active-credit-card: true
        currency: PEN
