spring:
  kafka:
    consumer:
      group-id: credit-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ntt.credit.model.kafka"
        spring.json.value.default.type: com.ntt.credit.model.kafka.ApplyPaymentCommand
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

credit:
  kafka:
    topics:
      apply-payment-command: apply-payment-command-topic
      payment-applied: payment-applied-topic
      payment-rejected: payment-rejected-topic
      debt-status-checked: debt-status-checked-topic
