services:
  # ==========================================
  # 0. Config Server
  # ==========================================
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: ntt_config_server
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/config-repo
    volumes:
      - type: bind
        source: ./config-repo
        target: /config-repo
        read_only: true
    networks:
      - ntt_network

  # ==========================================
  # 0.1 Eureka Server
  # ==========================================
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: ntt_eureka_server
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_INSTANCE_HOSTNAME: eureka-server
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - config-server
    networks:
      - ntt_network

  # ==========================================
  # 0.2 API Gateway
  # ==========================================
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: ntt_api_gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - config-server
      - eureka-server
    networks:
      - ntt_network

  # ==========================================
  # 1. MongoDB Database
  # ==========================================
  mongodb:
    image: mongo:6.0
    container_name: ntt_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ntt_network

  # 1.1 MongoDB UI (Mongo Express)
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: ntt_mongo_express
    restart: unless-stopped
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false" # Auth básica deshabilitada
    depends_on:
      - mongodb
    networks:
      - ntt_network

  # ==========================================
  # 2. Redis Cache Server
  # ==========================================
  redis:
    image: redis:7.0-alpine
    container_name: ntt_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ntt_network

  # ==========================================
  # 2.1 Auth Service
  # ==========================================
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: ntt_auth_service
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - config-server
      - eureka-server
    networks:
      - ntt_network

  # ==========================================
  # 3. Apache Kafka Ecosystem
  # ==========================================
  # 3.1 Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: ntt_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ntt_network

  # 3.2 Apache Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: ntt_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # Acceso externo vía localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - ntt_network

  # 3.3 Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ntt_kafka_ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      # Puerto 9000 (8080 reservado para API Gateway)
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ntt_local_cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - ntt_network

# ==========================================
# Volúmenes persistentes
# ==========================================
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  ntt_network:
    driver: bridge
